### ISSUE TITLE
NlpLocBackendHelper: android.os.DeadObjectException

### ISSUE THREAD

**Issue by cryptomilk** [microg/android_external_UnifiedNlpApi#7]
Using UnifiedNlp on Android 8.1 my log is filled with:

```
02-01 16:36:27.008  9284  9365 W NlpLocBackendHelper: 
02-01 16:36:27.008  9284  9365 W NlpLocBackendHelper: android.os.DeadObjectException
02-01 16:36:27.008  9284  9365 W NlpLocBackendHelper:   at android.os.BinderProxy.transactNative(Native Method)
02-01 16:36:27.008  9284  9365 W NlpLocBackendHelper:   at android.os.BinderProxy.transact(Binder.java:764)
02-01 16:36:27.008  9284  9365 W NlpLocBackendHelper:   at org.microg.nlp.api.LocationBackend$Stub$Proxy.update(LocationBackend.java:157)
02-01 16:36:27.008  9284  9365 W NlpLocBackendHelper:   at org.microg.nlp.location.BackendHelper.update(BackendHelper.java:71)
02-01 16:36:27.008  9284  9365 W NlpLocBackendHelper:   at org.microg.nlp.location.BackendFuser.update(BackendFuser.java:83)
02-01 16:36:27.008  9284  9365 W NlpLocBackendHelper:   at org.microg.nlp.location.ThreadHelper.run(ThreadHelper.java:73)
02-01 16:36:27.008  9284  9365 W NlpLocBackendHelper:   at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:457)
02-01 16:36:27.008  9284  9365 W NlpLocBackendHelper:   at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:307)
02-01 16:36:27.008  9284  9365 W NlpLocBackendHelper:   at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:302)
02-01 16:36:27.008  9284  9365 W NlpLocBackendHelper:   at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
02-01 16:36:27.008  9284  9365 W NlpLocBackendHelper:   at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
02-01 16:36:27.008  9284  9365 W NlpLocBackendHelper:   at java.lang.Thread.run(Thread.java:764)
```

Is there a way to get more debugging what is causing this?

I'm using the package from F-Droid.

**Comment by cryptomilk** [comment]
This happens if you completely turn off Location (e.g. in the quick pulldown menu)

**Comment by crabdancing** [comment]
I am getting this same error with GPS enabled.
