### ISSUE TITLE
Android P integration issues

### ISSUE THREAD

**Issue by pgera** [microg/android_external_UnifiedNlpApi#9]
I am able to build from master, and include the apk as a priv-app. However, going to settings->location just crashes the settings app. Here's the log:

```
10-12 09:49:02.231  1016  2029 W ActivityManager: Background start not allowed: service Intent { cmp=com.google.android.gms/org.microg.nlp.ui.SettingInjectorService (has extras) } to com.google.android.gms/org.microg.nlp.ui.SettingInjectorService from pid=1610 uid=1000 pkg=com.android.settings startFg?=false
10-12 09:49:02.231  1610  1610 D AndroidRuntime: Shutting down VM
--------- beginning of crash
10-12 09:49:02.231  1610  1610 E AndroidRuntime: FATAL EXCEPTION: main
10-12 09:49:02.231  1610  1610 E AndroidRuntime: Process: com.android.settings, PID: 1610
10-12 09:49:02.231  1610  1610 E AndroidRuntime: java.lang.IllegalStateException: Not allowed to start service Intent { cmp=com.google.android.gms/org.microg.nlp.ui.SettingInjectorService (has extras) }: app is in background uid UidRecord{a0ae399 u0a81 TRNB idle change:uncached procs:1 seq(0,0,0)}
10-12 09:49:02.231  1610  1610 E AndroidRuntime:        at android.app.ContextImpl.startServiceCommon(ContextImpl.java:1577)
10-12 09:49:02.231  1610  1610 E AndroidRuntime:        at android.app.ContextImpl.startServiceAsUser(ContextImpl.java:1549)
10-12 09:49:02.231  1610  1610 E AndroidRuntime:        at android.content.ContextWrapper.startServiceAsUser(ContextWrapper.java:680)
10-12 09:49:02.231  1610  1610 E AndroidRuntime:        at com.android.settings.location.SettingsInjector$Setting.startService(SettingsInjector.java:561)
10-12 09:49:02.231  1610  1610 E AndroidRuntime:        at com.android.settings.location.SettingsInjector$StatusLoadingHandler.handleMessage(SettingsInjector.java:457)
10-12 09:49:02.231  1610  1610 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:106)
10-12 09:49:02.231  1610  1610 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:193)
10-12 09:49:02.231  1610  1610 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:6669)
10-12 09:49:02.231  1610  1610 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
10-12 09:49:02.231  1610  1610 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
10-12 09:49:02.231  1610  1610 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
10-12 09:49:02.234  1016  2029 W ActivityManager:   Force finishing activity com.android.settings/.SubSettings
10-12 09:49:02.239  1610  1610 I Process : Sending signal. PID: 1610 SIG: 9
10-12 09:49:02.255  1016  2029 I WindowManager: WIN DEATH: Window{941e4e0 u0 com.android.settings/com.android.settings.SubSettings}
10-12 09:49:02.256  1016  1421 I ActivityManager: Process com.android.settings (pid 1610) has died: fore TOP
```

**Comment by pgera** [comment]
Sorry, wrong repo. Closing it. Will reopen in the main repo.
